#!/bin/bash

# This is a comment
echo "The current directory is:"
pwd
echo "The user logged in is:"
whoami

# display user home
echo "Home for current user is: $HOME"

# display dollar sign
echo "I have \$1"

# variables

grade=5
person="Adam"
echo "$person is a good boy, he is in grade $grade"

# getting information out of commands

mydir=`pwd`
user=$(whoami)

echo $mydir
echo $user

# math operations

var1=$((5+5))
echo $var1
var2=$(($var1*2))
echo $var2

# if-then construction

if pwd
then
echo "It works"
fi

user=gennadiy
if grep $user /etc/passwd
then
echo "The user $user exists"
fi

user=another
if grep $user /etc/passwd
then
echo "User $user exists"
else
echo "The user $user doesn't exist"
fi

user=anotherUser
if grep $user /etc/passwd
then
echo "The user $user exists"
elif ls /home
then
echo "the user doesn't exist but there i directory"
fi


# numbers comparison

val1=6
if [ $val1 -gt 5 ]
then
echo "$val1 greater than 5"
else
echo "$val1 not greater than 5"
fi

# strings comparison
user="gennadiy"
if [ $user = $USER ]
then
echo "The user $user is the current logged in user"
fi

# > and < need to be screened
val1=text
val2="another text"
if [ $val1 \> "$val2" ]
then
echo "$val1 is greater than $val2"
else
echo "$val1 is less than $val2"
fi

val1=Likegeeks
val2=likegeeks
if [ $val1 \> $val2 ]
then
echo "$val1 is greater than $val2"
else
echo "$val1 is less than $val2"
fi

# file checks
mydir=/gennadiy
if [ -d $mydir ]
then
echo "The $mydir directory exists"
cd $mydir
ls
else
echo "The $mydir does not exist"
fi










